drop table tb_listener;
drop table tb_talker;
drop table tb_chatroom;
drop table tb_rating;

CREATE TABLE tb_listener (
  `EMAIL` VARCHAR(50) NOT NULL,
  `PASSWORD` VARCHAR(50) NOT NULL,
  `NICKNAME` VARCHAR(50) NOT NULL,
  `SCORE` INT(11),
  `CONSULTING_TOPIC` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`EMAIL`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE tb_talker (
  `EMAIL` VARCHAR(50) NOT NULL,
  `PASSWORD` VARCHAR(50) NOT NULL,
  `NICKNAME` VARCHAR(50) NOT NULL,
  `STRESS_DEGREE` VARCHAR(2) NOT NULL,
  `CONSULTING_TOPIC` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`EMAIL`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE tb_rating (
  `IDX` int NOT NULL,
  `TALKER_EMAIL` VARCHAR(50) NOT NULL,
  `LISTENER_EMAIL` VARCHAR(50) NOT NULL,
  `HELPNESS` int NOT NULL,
  `PROFESSIONALISM` int not null,
  `SYMPATHY` int not null,
  `RESPONSIBILITY` int not null,
  `TOTAL_AVG` int not null,
  PRIMARY KEY (`IDX`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE tb_chatroom (
  `IDX` int NOT NULL,
  `TALKER_EMAIL` VARCHAR(50) NOT NULL,
  `TALKER_NICKNAME` VARCHAR(50) NOT NULL,
  `LISTENER_EMAIL` VARCHAR(50) NOT NULL,
  `LISTENER_NICKNAME` VARCHAR(50) NOT NULL,
  `LISTENER_RESPONSE` TINYINT(1) NOT NULL DEFAULT '0',
  `LAST_CHAT_TIME` TIMESTAMP,
  PRIMARY KEY (`IDX`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

insert into tb_user(EMAIL, PASSWORD, NICKNAME) values ('youngt1004', '1234', 'youngt1004');
insert into tb_rating (IDX, TALKER_EMAIL,LISTENER_EMAIL, HELPNESS, PROFESSIONALISM, SYMPATHY, RESPONSIBILITY, TOTAL_AVG) values (1,'kkyu_tk','ddd',1,1,1,1,1);

delete from tb_user where idx=3;

select sysdate();
select now();
SELECT * FROM tb_user;
SELECT * FROM tb_listener;
SELECT * FROM tb_rating;
SELECT * FROM tb_chatroom;