drop table tb_user;
drop table tb_listener;

CREATE TABLE tb_user (
  `IDX` INT(11) NOT NULL AUTO_INCREMENT,
  `EMAIL` VARCHAR(50) NOT NULL,
  `PASSWORD` VARCHAR(50) NOT NULL,
  `NICKNAME` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`IDX`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE tb_listener (
  `IDX` INT(11) NOT NULL AUTO_INCREMENT,
  `EMAIL` VARCHAR(50) NOT NULL,
  `PASSWORD` VARCHAR(50) NOT NULL,
  `NICKNAME` VARCHAR(50) NOT NULL,
  `JUMSU` INT(11),
  `CONSULTING_TOPIC` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`IDX`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE talker (
  `IDX` INT(11) NOT NULL AUTO_INCREMENT,
  `EMAIL` VARCHAR(50) NOT NULL,
  `PASSWORD` VARCHAR(50) NOT NULL,
  `NICKNAME` VARCHAR(50) NOT NULL,
  `STRESS_DEGREE` VARCHAR(2) NOT NULL,
  `CONSULTING_TOPIC` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`IDX`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

insert into tb_user(EMAIL, PASSWORD, NICKNAME) values ('youngt1004', '1234', 'youngt1004');
insert into tb_rating (IDX, TALKER_EMAIL,LISTENER_EMAIL, HELPNESS, PROFESSIONALISM, SYMPATHY, RESPONSIBILITY, TOTAL_AVG) values (1,'kkyu_tk','ddd',1,1,1,1,1);

delete from tb_user where idx=3;

select sysdate();
select now();
SELECT * FROM tb_user;
SELECT * FROM tb_listener;
SELECT * FROM tb_rating;
SELECT * FROM tb_chatroom;