#���̺� ����
drop table tb_user;
drop table tb_listener;

#ȸ�� ���̺�
CREATE TABLE tb_user (
  `IDX` INT(11) NOT NULL AUTO_INCREMENT,
  `EMAIL` VARCHAR(50) NOT NULL,
  `PASSWORD` VARCHAR(50) NOT NULL,
  `NICKNAME` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`IDX`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE tb_listener (
  `IDX` INT(11) NOT NULL AUTO_INCREMENT,
  `EMAIL` VARCHAR(50) NOT NULL,
  `PASSWORD` VARCHAR(50) NOT NULL,
  `NICKNAME` VARCHAR(50) NOT NULL,
  `JUMSU` INT(11),
  PRIMARY KEY (`IDX`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE talker (
  `IDX` INT(11) NOT NULL AUTO_INCREMENT,
  `EMAIL` VARCHAR(50) NOT NULL,
  `PASSWORD` VARCHAR(50) NOT NULL,
  `NICKNAME` VARCHAR(50) NOT NULL,
  `STRESS_DEGREE` VARCHAR(2),
  `CONSULTING_TOPIC` VARCHAR(50),
  PRIMARY KEY (`IDX`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

#ȸ���߰�  
insert into tb_user(EMAIL, PASSWORD, NICKNAME) values ('youngt1004', '1234', 'youngt1004');

#ȸ������
delete from tb_user where idx=3;

#ȸ���˻�
SELECT * FROM tb_user;
